Mysql:
  Ip: "115.190.57.118"
  Port: 3306
  User: "root"
  Password: "4ay1nkal3u8ed77y"
  Db: "yuedemo"
Redis:
  Addr: "115.190.57.118:6379"
  Db: 0
  Password: "4ay1nkal3u8ed77y"
  MaxIdle: 10
  PoolSize: 20
Log:
  Level: "debug"
  Path: "./logs/app.log"
  MaxSize: 100
  MaxBackups: 10
  MaxAge: 7
  Compress: "true"
  Format: "console"
  ConsoleEnable: "true"
